version: '2'
services:
  backend:
    build: ./server/
    volumes:
     - ./server:/app
    restart: always
    ports:
     - "8000:8000"
    expose: 
     - "8000"
  client:
    build: ./client/
    volumes:
      - ./client:/app
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:80"
